version: '3.6'
services:

  riak:
    image: riak.local:latest
    build:
      context: ./riak/
      dockerfile: Dockerfile
    container_name: riak
    hostname: riak
    command: tail -f /dev/null

  safe:
    image: safe.local:latest
    build:
      context: ./safe/
      dockerfile: Dockerfile
    container_name: safe
    hostname: safe
    ports:
      - '7777:7777'
    environment:
      - RIAK_IP=riak
      - SLANG_SCRIPT=strong.slang
      - SLANG_CONF=strong.conf.slang
      - STRONG_ROOT_PUB=strong-1.pub
    volumes:
      - ../safe-apps/strong/strong.slang:/imports/strong.slang 
      - ../safe-apps/strong/strong.conf.slang:/imports/strong.conf.slang
      - ./principalkeys:/principalkeys
